// <auto-generated />
using System;
using Metaldle.infrastructure.Metalbands;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Metaldle.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217112642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Metaldle.Infrastructure.Metalbands.Metalband", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContinentAttribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListAttribute1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListAttribute2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListAttribute3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumericAttribute1")
                        .HasColumnType("integer");

                    b.Property<int>("NumericAttribute2")
                        .HasColumnType("integer");

                    b.Property<string>("RegionAttribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAttribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MetalBands");
                });
#pragma warning restore 612, 618
        }
    }
}
