namespace Metaldle.Core.Ports;

using Metaldle.Core.Domain.Entities;

public interface ISessionRepository
{
    // Get today's active session for an anonymous session ID
    Task<GameSession?> GetTodaysSessionAsync(string sessionId, DateOnly date);
    
    // Create or update a session
    Task SaveSessionAsync(GameSession session);
    
    // Delete a session (when game completes or user wants to reset)
    Task DeleteSessionAsync(string sessionId, DateOnly date);
    
    // Check if session has an active game today
    Task<bool> HasActiveSessionAsync(string sessionId, DateOnly date);
}

/*
## **Key Points**

    1. **`sessionId` is a `string`** - This is the anonymous UUID generated by the frontend (e.g., `"a3f2b1c4-5678-90ab-cdef-1234567890ab"`)

2. **Date-based lookup** - We use `DateOnly date` because each day has a unique game. The session is tied to both the sessionId AND the date.

3. **Redis key structure** (implementation detail for later):
    ```
Key: game_session:{sessionId}:{date}
Value: JSON serialized GameSession
TTL: 24 hours
*/